#!/usr/bin/env bash
# install.sh — Universal Factory CLI Installer
# Usage: chmod +x install.sh && ./install.sh

set -euo pipefail

FACTORY_PATH="$(pwd)"
BIN_DIR="$HOME/.local/bin"
FACTORY_BIN="$BIN_DIR/factory"

echo "======================================================"
echo " AI Software Factory — CLI Installer"
echo "======================================================"
echo " Factory path: $FACTORY_PATH"
echo ""

# ── 1. Create ~/.local/bin if needed ─────────────────────

mkdir -p "$BIN_DIR"

# ── 2. Write the factory wrapper ─────────────────────────

cat > "$FACTORY_BIN" << 'FACTORY_EOF'
#!/usr/bin/env bash
# factory — Universal AI Agent CLI Wrapper
# Generated by install.sh — do not edit FACTORY_PATH manually; re-run install.sh

FACTORY_PATH="__FACTORY_PATH__"

usage() {
  echo "Usage: factory <agent-folder> [engine] [query...]"
  echo ""
  echo "  agent-folder  One of the AgenteXX_* folders (e.g. Agente00_TechLead)"
  echo "  engine        claude (default) | gemini"
  echo "  query         Optional prompt. Omit to enter interactive mode."
  echo ""
  echo "Examples:"
  echo "  factory Agente00_TechLead"
  echo "  factory Agente02_SoftwareArchitect claude 'Design a REST API for payments'"
  echo "  factory Agente06_QaEngineer gemini 'Write E2E tests for the login flow'"
  echo ""
  echo "Or use the short aliases set up by install.sh:"
  echo "  techlead   po   architect   engineer   devbackend   devfrontend"
  echo "  qa         devsecops   devops   uxui   dataengineer"
}

AGENT_FOLDER="${1:-}"
if [[ -z "$AGENT_FOLDER" ]]; then
  usage
  exit 1
fi

ENGINE="${2:-claude}"
shift 2 2>/dev/null || shift "${#@}" 2>/dev/null
QUERY="$*"

AGENT_DIR="$FACTORY_PATH/$AGENT_FOLDER"
PROMPT_FILE="$AGENT_DIR/prompt.md"

if [[ ! -d "$AGENT_DIR" ]]; then
  echo "Error: agent folder not found: $AGENT_DIR" >&2
  echo "Available agents:" >&2
  ls "$FACTORY_PATH" | grep '^Agente' >&2
  exit 1
fi

if [[ ! -f "$PROMPT_FILE" ]]; then
  echo "Error: prompt.md not found in $AGENT_DIR" >&2
  exit 1
fi

SYSTEM="$(cat "$PROMPT_FILE")"

case "$ENGINE" in
  claude)
    if [[ -n "$QUERY" ]]; then
      exec claude --system-prompt "$SYSTEM" -p "$QUERY" --add-dir "$AGENT_DIR"
    else
      exec claude --system-prompt "$SYSTEM" --add-dir "$AGENT_DIR"
    fi
    ;;
  gemini)
    if [[ -n "$QUERY" ]]; then
      exec gemini --system-prompt "$SYSTEM" -p "$QUERY"
    else
      exec gemini --system-prompt "$SYSTEM"
    fi
    ;;
  *)
    echo "Error: unknown engine '$ENGINE'. Use 'claude' or 'gemini'." >&2
    exit 1
    ;;
esac
FACTORY_EOF

# Embed the actual factory path into the wrapper
sed -i "s|__FACTORY_PATH__|${FACTORY_PATH}|g" "$FACTORY_BIN"
chmod +x "$FACTORY_BIN"
echo "[OK] Factory wrapper written to $FACTORY_BIN"

# ── 3. Detect shell and inject aliases ───────────────────

detect_rc() {
  if [[ -n "${ZSH_VERSION:-}" ]] || [[ "$SHELL" == */zsh ]]; then
    echo "$HOME/.zshrc"
  else
    echo "$HOME/.bashrc"
  fi
}

RC_FILE="$(detect_rc)"
ALIAS_MARKER="# BEGIN factory-aliases (ai_software_factory)"
ALIAS_END_MARKER="# END factory-aliases (ai_software_factory)"

inject_aliases() {
  local rc="$1"

  # Guard: skip if already present
  if grep -q "$ALIAS_MARKER" "$rc" 2>/dev/null; then
    echo "[SKIP] Aliases already present in $rc"
    return 0
  fi

  cat >> "$rc" << ALIASES_EOF

$ALIAS_MARKER
# Generated by $FACTORY_PATH/install.sh — remove this block to uninstall aliases
alias techlead='factory Agente00_TechLead claude'
alias po='factory Agente01_ProductOwner claude'
alias architect='factory Agente02_SoftwareArchitect claude'
alias engineer='factory Agente03_SoftwareEngineer claude'
alias devbackend='factory Agente04_DevBackend claude'
alias devfrontend='factory Agente05_DevFrontend claude'
alias qa='factory Agente06_QaEngineer claude'
alias devsecops='factory Agente07_DevSecOps claude'
alias devops='factory Agente08_DevOps claude'
alias uxui='factory Agente09_UxUiDesigner claude'
alias dataengineer='factory Agente10_DataIntegrationEngineer claude'
$ALIAS_END_MARKER
ALIASES_EOF

  echo "[OK] Aliases injected into $rc"
}

inject_aliases "$RC_FILE"

# ── 4. Ensure ~/.local/bin is on PATH ────────────────────

if ! grep -q 'export PATH.*\.local/bin' "$RC_FILE" 2>/dev/null; then
  echo "" >> "$RC_FILE"
  echo "# Added by ai_software_factory install.sh" >> "$RC_FILE"
  echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$RC_FILE"
  echo "[OK] Added \$HOME/.local/bin to PATH in $RC_FILE"
else
  echo "[SKIP] \$HOME/.local/bin already in PATH"
fi

# ── 5. Done ───────────────────────────────────────────────

echo ""
echo "======================================================"
echo " Installation complete!"
echo "======================================================"
echo ""
echo " To activate in the current shell, run:"
echo "   source $RC_FILE"
echo ""
echo " Then use any of these shortcuts:"
echo "   techlead       'Define project scope and quality gates'"
echo "   po             'Write user stories and acceptance criteria'"
echo "   architect      'Design system architecture and ADRs'"
echo "   engineer       'Implement backend/frontend logic'"
echo "   devbackend     'Build APIs, services, database layers'"
echo "   devfrontend    'Build UI components and pages'"
echo "   qa             'Write and run tests'"
echo "   devsecops      'Security audits and hardening'"
echo "   devops         'Infrastructure, CI/CD, deployment'"
echo "   uxui           'UX research, wireframes, prototypes'"
echo "   dataengineer   'Data pipelines and integrations'"
echo ""
echo " Or call the wrapper directly:"
echo "   factory Agente00_TechLead claude 'Review this PR'"
echo ""
