#Requires -Version 7
<#
.SYNOPSIS
    Pester tests for uninstall.ps1

    Tests that can run without a full install:
    - Syntax (AST parse)
    - Parameter block: -KeepKnowledge, -Full, -WhatIf, -Force
    - -WhatIf mode: no files are deleted (uses $TestDrive)
    - Safety marker: only removes agent files with AUTO-GENERATED marker
    - Function definitions (Remove-IfExists, Write-OK, etc.)
#>

BeforeAll {
    $factoryRoot = (Resolve-Path "$PSScriptRoot\..\.." ).Path
    $script      = Join-Path $factoryRoot "uninstall.ps1"
}

Describe "uninstall.ps1 — syntax and structure" {

    It "script file exists" {
        $script | Should -Exist
    }

    It "parses without syntax errors" {
        $errors = $null
        $null = [System.Management.Automation.Language.Parser]::ParseFile(
            $script, [ref]$null, [ref]$errors
        )
        $errors | Should -BeNullOrEmpty
    }

    It "declares -KeepKnowledge parameter" {
        $ast = [System.Management.Automation.Language.Parser]::ParseFile(
            $script, [ref]$null, [ref]$null
        )
        $paramBlock = $ast.Find(
            { $args[0] -is [System.Management.Automation.Language.ParamBlockAst] }, $true
        )
        $paramBlock | Should -Not -BeNullOrEmpty
        $names = $paramBlock.Parameters.Name.VariablePath.UserPath
        $names | Should -Contain 'KeepKnowledge'
    }

    It "declares -Full parameter" {
        $ast = [System.Management.Automation.Language.Parser]::ParseFile(
            $script, [ref]$null, [ref]$null
        )
        $paramBlock = $ast.Find(
            { $args[0] -is [System.Management.Automation.Language.ParamBlockAst] }, $true
        )
        $names = $paramBlock.Parameters.Name.VariablePath.UserPath
        $names | Should -Contain 'Full'
    }

    It "declares -WhatIf parameter" {
        $ast = [System.Management.Automation.Language.Parser]::ParseFile(
            $script, [ref]$null, [ref]$null
        )
        $paramBlock = $ast.Find(
            { $args[0] -is [System.Management.Automation.Language.ParamBlockAst] }, $true
        )
        $names = $paramBlock.Parameters.Name.VariablePath.UserPath
        $names | Should -Contain 'WhatIf'
    }

    It "declares -Force parameter" {
        $ast = [System.Management.Automation.Language.Parser]::ParseFile(
            $script, [ref]$null, [ref]$null
        )
        $paramBlock = $ast.Find(
            { $args[0] -is [System.Management.Automation.Language.ParamBlockAst] }, $true
        )
        $names = $paramBlock.Parameters.Name.VariablePath.UserPath
        $names | Should -Contain 'Force'
    }

    It "defines Remove-IfExists helper function" {
        $content = Get-Content $script -Raw
        $content | Should -Match 'function Remove-IfExists'
    }

    It "checks AUTO-GENERATED safety marker before removing agent files" {
        $content = Get-Content $script -Raw
        $content | Should -Match 'AUTO-GENERATED'
    }
}

Describe "uninstall.ps1 — WhatIf mode: no files deleted" {

    It "does not delete a simulated agent file when -WhatIf is passed" {
        # Create a fake agent file in TestDrive with the safety marker
        $fakeAgentsDir = Join-Path $TestDrive ".claude\agents"
        New-Item -ItemType Directory -Path $fakeAgentsDir -Force | Out-Null
        $fakeAgent = Join-Path $fakeAgentsDir "techlead.md"
        Set-Content $fakeAgent "# AUTO-GENERATED BY ai_software_factory`nsome content" -Encoding UTF8

        # Run uninstall with -WhatIf via child process, redirecting USERPROFILE to TestDrive
        $env_backup = $env:USERPROFILE
        try {
            $result = pwsh -NonInteractive -Command "
                `$env:USERPROFILE = '$TestDrive'
                & '$script' -WhatIf -Force
            " 2>&1
        } finally {
            $env:USERPROFILE = $env_backup
        }

        # File must still exist (WhatIf should not delete it)
        $fakeAgent | Should -Exist
    }

    It "produces [WHAT] output lines when -WhatIf is used" {
        $result = pwsh -NonInteractive -Command "
            `$env:USERPROFILE = '$TestDrive'
            `$env:APPDATA     = '$TestDrive'
            & '$script' -WhatIf -Force
        " 2>&1 | Out-String

        # WhatIf mode must output [WHAT] or [SKIP] lines, never [OK] for removals
        # (it may say [SKIP] if files don't exist, which is also valid)
        $result | Should -Match '(?i)(WHAT|WhatIf|what-if|preview|nenhuma)'
    }
}

Describe "uninstall.ps1 — safety marker enforcement" {

    It "script content checks for factory marker before removal" {
        $content = Get-Content $script -Raw
        # The safety check pattern: Select-String or -match on AUTO-GENERATED
        $content | Should -Match '(?i)(Select-String|isFactoryAgent|AUTO-GENERATED)'
    }

    It "skips agent files without safety marker" {
        # Create a fake agent file WITHOUT the safety marker
        $fakeAgentsDir = Join-Path $TestDrive ".claude\agents"
        New-Item -ItemType Directory -Path $fakeAgentsDir -Force | Out-Null
        $fakeAgent = Join-Path $fakeAgentsDir "techlead.md"
        Set-Content $fakeAgent "# Some external agent without factory marker" -Encoding UTF8

        $result = pwsh -NonInteractive -Command "
            `$env:USERPROFILE = '$TestDrive'
            `$env:APPDATA     = '$TestDrive'
            & '$script' -Force
        " 2>&1 | Out-String

        # File should survive because it has no AUTO-GENERATED marker
        $fakeAgent | Should -Exist
        $result    | Should -Match '(?i)(warn|ignorando|externo|sem marcador|nao tem marcador)'
    }
}
